### ISSUE TITLE
Cannot save classes properly

### ISSUE THREAD

**Issue by DylanSu1216** [nkaaf/Arduino-List#39]
my library version is 2.1.4
![image](https://github.com/nkaaf/Arduino-List/assets/106652618/006c4a2e-f11f-4604-8393-fa221e86aba2)

and my arduino code is like
```
 List<String> aa;
  aa.add("Hellp");
  Serial.println(aa.getSize());
  for (int i = 0; i < aa.getSize(); i++) {

    Serial.println(aa[i]);
  }
```

but Serial.println(aa[i]) is not my expected

![image](https://github.com/nkaaf/Arduino-List/assets/106652618/fd86a2c4-8bd8-44af-acb5-3fadbf0df69c)

I really appreciate your help

**Comment by DylanSu1216** [comment]
> Hi,
> 
> thank you very much for providing this information :) These have helped me to reproduce the problem. You are right, this is not the expected result and there is indeed an error.
> 
> The problem is that the datatype of the rvalue "Hellp" is not a primitive, but calls a constructor of the class "String" (I think this constructor is called "converting constructor" in C++). And this causes some bug in my code.
> 
> There is a workaround for you until I fix the problem 😄
> 
> ```c++
>   List<String> aa;
>   String h = "Hellp";
>   aa.add(h);
>   Serial.println(aa.getSize());
>   for (int i = 0; i < aa.getSize(); i++) {
> 
>     Serial.println(aa[i]);
>   }
> ```
> 
> I would be grateful if you could try this and report any further problems. In the meantime, I will try to fix the error.
> 
> Thank you very much 👍
my English is poor and I no offense.
Thank you help,your library is very useful !!!!!
it work!! thank you!!!!!
 ```
List<String> aa;
  String h = "Hellp";
  aa.add(h);
  Serial.println(aa.getSize());
  for (int i = 0; i < aa.getSize(); i++) {

    Serial.println(aa[i]);
  }
```



and this is new bug.

```
//Global variables
List<String> RowDataStrList;

void TestFunc() {
  RowDataStrList.clear();
  int val_1 = 100;
  String Str_val = String(val_1);
  RowDataStrList.add(Str_val);
}

void loop(){
  TestFunc();
  Serial.println(RowDataStrList.getSize());
  for (int i = 0; i < RowDataStrList.getSize(); i++) {

    Serial.println(RowDataStrList[i]);
  }
}
```
result is
![image](https://github.com/nkaaf/Arduino-List/assets/106652618/a3c3e926-7375-43ec-9594-802e43d17906)

**Comment by nkaaf** [comment]
Hi, thanks for all the information. I have looked at the scenarios and am currently rewriting the library. The changes will be internally larger than initially thought, so it will be version 3 of the library. I need a few more days before I can publish the final version, because I am still working on the changes. I hope this is not a big problem for you and your project. I apologize for any inconvenience.

**Comment by DylanSu1216** [comment]
> Hi, thanks for all the information. I have looked at the scenarios and am currently rewriting the library. The changes will be internally larger than initially thought, so it will be version 3 of the library. I need a few more days before I can publish the final version, because I am still working on the changes. I hope this is not a big problem for you and your project. I apologize for any inconvenience.

Thanks a lot. 💖💖

**Comment by nkaaf** [comment]
Hello,
I have now made a pre-release of the 3.0.0 version (https://github.com/nkaaf/Arduino-List/releases/tag/v3.0.0pre1). There you can download the ZIP file and add it to your IDE. But I have to say that this is a pre-release, which means that not all functions are available (therefore not meant for production!).
Not functional:
- (Im)Mutable DoubleLinkedLists
- Mutable SingleLinkedLists (aka. List)
- toArray/fromArray/sort function of SingleLinkedLists (aka. List)

Your use case (immutable SingleLinkedList (aka. List)) should be functional. I would love it if you can try this out.
Unfortunately I can't change the version number for the Arduino IDE to for example: 3.0.0pre1. Therefore the library is already shown as 3.0.0. You can add the library using the built-in function (Include .zip - https://support.arduino.cc/hc/en-us/articles/5145457742236-Add-libraries-to-Arduino-IDE). But you have to remove the already installed library first.
As soon as the final version 3.0.0 is released, I will write again here in the issue, so you will get the notification. After that you have to remove the library from the manager again to download the library with the manager directly from Arduino.

Thank you for waiting and understanding 🙏🏼
