### ISSUE TITLE
[AbstractList.hpp] size_t not found in 3.0.0

### ISSUE THREAD

**Issue by NoovasG** [nkaaf/Arduino-List#45]
Hello,
I just installed your List library (version 3.0.0). When I just add #include <List.hpp> and try to compile I am getting errors.

In file included from C:\Users\User\Documents\Arduino\libraries\List\src/SingleLinkedList.hpp:29,
                 from C:\Users\User\Documents\Arduino\libraries\List\src/List.hpp:46,
                 from C:\Users\User\Documents\Arduino\libraries\Grove_3Axis_Compass_V2.0_BMM150\examples\compass\compass.ino:1:
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:36:3: error: 'size_t' does not name a type
   size_t size = 0;         /// Size of the list.
   ^~~~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:36:3: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:1:1:
+#include <cstddef>
 /*!
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:36:3:
   size_t size = 0;         /// Size of the list.
   ^~~~~~
In file included from C:\Users\User\Documents\Arduino\libraries\List\src/SingleLinkedList.hpp:29,
                 from C:\Users\User\Documents\Arduino\libraries\List\src/List.hpp:46,
                 from C:\Users\User\Documents\Arduino\libraries\Grove_3Axis_Compass_V2.0_BMM150\examples\compass\compass.ino:1:
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:209:40: error: 'size_t' does not name a type
   void addAll(int index, T *arr, const size_t arrSize) {
                                        ^~~~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:209:40: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:222:29: error: 'size_t' does not name a type
   void addAll(T *arr, const size_t arrSize) {
                             ^~~~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:222:29: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
In file included from C:\Users\User\Documents\Arduino\libraries\List\src/SingleLinkedList.hpp:29,
                 from C:\Users\User\Documents\Arduino\libraries\List\src/List.hpp:46,
                 from C:\Users\User\Documents\Arduino\libraries\Grove_3Axis_Compass_V2.0_BMM150\examples\compass\compass.ino:1:
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'void AbstractList<T>::increaseSize()':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:107:25: error: 'size' was not declared in this scope
   void increaseSize() { size++; }
                         ^~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'void AbstractList<T>::decreaseSize()':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:113:25: error: 'size' was not declared in this scope
   void decreaseSize() { size--; }
                         ^~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'void AbstractList<T>::resetSize()':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:118:22: error: 'size' was not declared in this scope
   void resetSize() { size = 0; }
                      ^~~~
In file included from C:\Users\User\Documents\Arduino\libraries\List\src/SingleLinkedList.hpp:29,
                 from C:\Users\User\Documents\Arduino\libraries\List\src/List.hpp:46,
                 from C:\Users\User\Documents\Arduino\libraries\Grove_3Axis_Compass_V2.0_BMM150\examples\compass\compass.ino:1:
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'void AbstractList<T>::addAll(int, T*, int)':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:210:10: error: 'size_t' was not declared in this scope
     for (size_t i = 0; i < arrSize; ++i) {
          ^~~~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:210:10: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:210:24: error: 'i' was not declared in this scope
     for (size_t i = 0; i < arrSize; ++i) {
                        ^
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'void AbstractList<T>::addAll(T*, int)':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:223:10: error: 'size_t' was not declared in this scope
     for (size_t i = 0; i < arrSize; ++i) {
          ^~~~~~
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:223:10: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:223:24: error: 'i' was not declared in this scope
     for (size_t i = 0; i < arrSize; ++i) {
                        ^
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp: In member function 'int AbstractList<T>::getSize() const':
C:\Users\User\Documents\Arduino\libraries\List\src/AbstractList.hpp:332:32: error: 'size' was not declared in this scope
   int getSize() const { return size; }
                                ^~~~

exit status 1

Compilation error: exit status 1

with version 2.1.4 there are no errors when #include <List.hpp> .

**Comment by nkaaf** [comment]
Hi, thank you for your submission.
I have fixed the issue in Release v3.0.1 (https://github.com/nkaaf/Arduino-List/releases/tag/v3.0.1). It will be available soon in the Arduino-Library Registry and sooner in the PlatformIO Registry.

If you encounter further problems or ideas, don't hesitate to submit an issue 😄
